### ISSUE TITLE
Android 11 Compatible?

### ISSUE THREAD

**Issue by m-anshuman2166** [Abhay-cloud/Instagram-Video-Downloader-Library#3]
Is library compatible to Android 11?

**Comment by Abhay-cloud** [comment]
Yes @ansh2166

**Comment by m-anshuman2166** [comment]
Dope work sir! I will make it compatible to be used as a plugin in MIT Appinventor and will surely give you credits

**Comment by Abhay-cloud** [comment]
Go for it!
I would like to see it. @ansh2166
